### ISSUE TITLE
WHAT IS NEXT?

### ISSUE THREAD

**Issue by danielstuart14** [danielstuart14/Altis-Life#41]
<b>My to-do list can be found here:</b> https://trello.com/b/9urCslRT/altis-life
So, don't ask for features that are already added to this list.

**Comment by tkcjesse** [comment]
Any plans to use Colins persistent wanted system like before?

**Comment by sargken** [comment]
Its not on his todo list but i can see what i can do if time opens up.

**Comment by tkcjesse** [comment]
Yeah, I mean I'm willing to submit the changes for it. However if they'll be ignored I won't bother sharing it. Just not sure on the road-map as to how far out AL will be developed out now. Since Tonic doesn't give a hoot.

**Comment by sargken** [comment]
Make a Merge Request and im sure Dan will look it over.

**Comment by sargken** [comment]
I agree with your Tonic Part, which still sucks be cause he still owns the main master branch, so even if i wanted to help contribute more. AKA I developed a Takistan Life Mission from the Altis Framework, added in Opfor and Insurgents as Independent instead of Medic. Medic im making into a civilian thing as a job they can do. Just like United Nations and PMC. If you know what Takistan Life Revolution is its going to be similar. What say do i have in anything major though @tkcjesse. Sorry all for the offtopic rant.

**Comment by danielstuart14** [comment]
If it isn't bugged as it was on Itsyuka branch, I'll merge.

**Comment by tkcjesse** [comment]
@danielstuart14 I believe his branch still is muffed up with the wanted list not displaying if 2+ people.

**Comment by danielstuart14** [comment]
https://github.com/ArmaLife/Altis

**Comment by Heavybob** [comment]
*Repost all issues to this git*
https://github.com/ArmaLife/Altis/issues

This Git is being discontinued.
